# Generated by Django 3.0.5 on 2020-05-24 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='sno',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
